"""initial schema

Revision ID: 812ed6b10487
Revises:
Create Date: 2026-08-01 00:29:15.546995

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "812ed6b10487"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
